---
title: "Fintech"
author: "Derik Suria"
output: html_document
date: "2022-09-14"
---

## Loading Packages 

```{r setup, include=FALSE}
install.packages("tidyverse")
install.packages("padr")
install.packages("zoo")
install.packages("lubridate")
```

```{r}
library(tidyverse)
library(padr)
library(zoo)
library(lubridate)
```

## Reading csv Files

```{r reading files}
test <- read_csv("fred5y.csv") 
test
```

```{r}
fred5yfor <- read_csv("fred5yforward.csv") 
fred5yfor
```

```{r}
fred10y <- read_csv("fred10y.csv") %>%
  rename(inf = "10-Year Breakeven Inflation Rate, Percent, Daily, Not Seasonally Adjusted") %>%
  select(T10YIE, inf)
fred10y 
```

```{r}
crypt <- read_csv("crypt.csv") %>%
  rename(index = "S&P Cryptocurrency Broad Digital Market Index (USD)",
         date = "Effective date") %>%
  select(date, index) %>%
  mutate(date = parse_date(date, format = "%m/%d/%y"))
```

```{r data from new gold}
gold <- read_csv("gold.csv") %>%
  mutate(Date = parse_date(Date, format = "%m/%d/%y")) %>%
  select(Date, Price)
```

```{r ETF}
etf <- read_csv("etf.csv") %>%
  select(Date, Close) %>%
  mutate(Date = parse_date(Date, format = "%d/%m/%Y"))
```

## Filling Missing Dates using pad() 

```{r}
data_new <- pad(test) #https://statisticsglobe.com/insert-rows-for-missing-dates-in-r
d10 <- pad(fred10y)
d5f <- pad(fred5yfor)
cry <- pad(crypt)
gld <- pad(gold)
etfc <- pad(etf)
```

## Interpolating Missing Values using na.approx()

```{r}
d5 <- data_new %>%
  rename(ifl = "5-Year Breakeven Inflation Rate, Percent, Daily, Not Seasonally Adjusted") %>%
  mutate(ifl = na.approx(ifl)) #https://www.statology.org/r-interpolate-missing-values/, https://stats.stackexchange.com/questions/107505/interpolating-time-series
d5 <- data2 %>% 
  select(T5YIE, ifl)
d5
```

```{r}
d10clean <- d10 %>%
  mutate(inf = na.approx(inf)) 
```

```{r}
d5clean <- d5f %>%
  mutate(T5YIFR = na.approx(T5YIFR)) 
```

```{r}
cryptclean <- cry %>%
  mutate(index = na.approx(index)) 
```

```{r}
goldclean <- gld %>%
  mutate(Price = na.approx.default(Price, rule = 2)) #https://stackoverflow.com/questions/7317607/interpolate-na-values-in-a-data-frame-with-na-approx
```

```{r}
etfclean <- etfc %>%
  mutate(Close = na.approx(Close)) 
```

## Exporting Clean Data

```{r}
write_csv(d5, "/Users/oneinchdong/Desktop/ECON182/5ybreakevenclean.csv")
write_csv(d10clean, "/Users/oneinchdong/Desktop/ECON182/10ybreakevenclean.csv")
write_csv(d5clean, "/Users/oneinchdong/Desktop/ECON182/5yforwardclean.csv")
write_csv(cryptclean, "/Users/oneinchdong/Desktop/ECON182/cryptclean.csv")
write_csv(goldclean, "/Users/oneinchdong/Desktop/ECON182/goldclean.csv")
write_csv(etfclean, "/Users/oneinchdong/Desktop/ECON182/etfclean.csv")
```

## Calculate Rolling Correlation

```{r bitcoin vs gold}
cryptgold <- left_join(goldclean %>% subset(Date > "2017-02-28"), cryptclean %>% rename(Date = date), by = "Date") # https://stackoverflow.com/questions/22554166/select-data-after-specific-date
```

```{r}
rollapply(cryptgold, width = 100, function(x) cor(cryptgold[2],cryptgold[3], use = "complete.obs"), by.column=FALSE)
```

```{r}
rollapply(cryptgold, width = 3, function(x) cor(cryptgold[,2],cryptgold[,3], use = "complete.obs"), by.column=FALSE)
```

```{r}
cor(cryptgold[2],cryptgold[3], use = "complete.obs")
```

## Rolling Correlation using For Loops

```{r}
correlation = cor(cryptgold[2],cryptgold[3], use = "complete.obs")
correlation
```

```{r}
i = 1
output = NULL
while(i<675){
  correlation = cor(cryptgold$Close[i:(2 + i)],cryptgold$index[i:(2 + i)], use = "complete.obs")
  output = rbind(output, correlation)
  i = i+1
}
output
```


```{r}
output = NULL
correlation1 = NULL
for (i in 1:2035) {
  correlation1 = cor(Close[i])
}

dim(output)
plot(output)
```

```{r}
write_csv(cryptgold, "/Users/oneinchdong/Desktop/ECON182/cryptgoldclean.csv")
```

# Granger Causality Test

```{r}
install.packages("lmtest")
library (lmtest)
```

```{r}
cause <- read_csv("causalitytest.csv")
```

## BTC DR vs Response Variables

```{r BTC vs 5YRBE}
grangertest(BTCDR ~ FBE, order = 1, data = cause) # p-value = 0.05791
grangertest(FBE ~ BTCDR, order = 1, data = cause) # p-value = 1.351e-06
```

```{r BTC vs 5YRFL}
grangertest(BTCDR ~ FFL, order = 1, data = cause) # p-value = 0.963
grangertest(FFL ~ BTCDR, order = 1, data = cause) # p-value = 0.09846
```

```{r}
grangertest(BTCDR ~ TBE, order = 1, data = cause) # p-value = 0.2077
grangertest(TBE ~ BTCDR, order = 1, data = cause) # p-value = 8.625e-05
```

## ETF DR vs Response Variables

```{r BTC vs 5YRBE}
grangertest(ETFDR ~ FBE, order = 1, data = cause) # p-value = 1.584e-07
grangertest(FBE ~ ETFDR, order = 1, data = cause) # p-value = 0.05833
```

```{r BTC vs 5YRFL}
grangertest(ETFDR ~ FFL, order = 1, data = cause) # p-value = 0.01946
grangertest(FFL ~ ETFDR, order = 1, data = cause) # p-value = 0.2152
```

```{r}
grangertest(ETFDR ~ TBE, order = 1, data = cause) # p-value = 4.03e-05 
grangertest(TBE ~ ETFDR, order = 1, data = cause) # p-value = 0.09051
```

## GOLD DR vs Response Variables

```{r BTC vs 5YRBE}
grangertest(GOLDDR ~ FBE, order = 1, data = cause) # p-value = 0.3948
grangertest(FBE ~ GOLDDR, order = 1, data = cause) # p-value = 0.5691
```

```{r BTC vs 5YRFL}
grangertest(GOLDDR ~ FFL, order = 1, data = cause) # p-value = 0.5155
grangertest(FFL ~ GOLDDR, order = 1, data = cause) # p-value = 0.8524
```

```{r}
grangertest(GOLDDR ~ TBE, order = 1, data = cause) # p-value = 0.2863
grangertest(TBE ~ GOLDDR, order = 1, data = cause) # p-value = 0.8398
```

## CRYPT DR vs Response Variables

```{r BTC vs 5YRBE}
grangertest(CRYPTDR ~ FBE, order = 1, data = cause) # p-value = 0.1809
grangertest(FBE ~ CRYPTDR, order = 1, data = cause) # p-value = 3.901e-07
```

```{r BTC vs 5YRFL}
grangertest(CRYPTDR ~ FFL, order = 1, data = cause) # p-value = 0.4347
grangertest(FFL ~ CRYPTDR, order = 1, data = cause) # p-value = 0.0003644
```

```{r}
grangertest(CRYPTDR ~ TBE, order = 1, data = cause) # p-value = 0.2737
grangertest(TBE ~ CRYPTDR, order = 1, data = cause) # p-value = 7.832e-08
```